- name: frontend server configuration
  hosts: frontend
  become: true

  tasks:
    - name: disable nginx module
      ansible.builtin.command: dnf module disable nginx -y

    - name: enable nginx module stream 1.24
      ansible.builtin.command: dnf module enable nginx:1.24 -y

    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: start nginx service
      ansible.builtin.service:
        name: nginx
        state: started

    - name: remove default nginx html content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: recreate html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: download frontend content
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /tmp/frontend.zip

    - name: unzip frontend content
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: copy nginx.conf
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
