- name: configure redis server
  hosts: redis
  become: true
  tasks:
   - name: disable redis
     ansible.buitlin.dnf:
     name: redis
     state: disabled
    
   - name: enable redis module stream 7
     ansible.buiiltin.dnf:
     name: redis:7
     state: enabled

   - name: install redis
     ansible.buitlin.dnf:
     name: redis
     state: present

   - name: allow remote connections
     ansible.builtin.replace:
     path: /etc/redis/redis.conf
     regexp: '127.0.0.1' 
     replace: '0.0.0.0'

   - name: disable protected mode
     ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: protected-mode no

   - name: enable and start redis service
     ansible.builtin.service:
       name: redis
       state: started
       enabled: yes   