- name: configuring user server
  hosts: user
  become: true
  tasks:
   - name: disable nodejs module
     ansible.builtin.dnf:
      name: nodejs
      state: disabled
   
    - name: enable nodejs module stream 20
      ansible.builtin.dnf:
      name: nodejs:20
      state: enabled
   
    - name: install nodejs
      ansible.builtin.dnf:
      name: nodejs
      state: present

    - name: create roboshop system user
      ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
  
   - name: create app directory
     ansible.builtin.file:
      path: /app
      state: directory
   
   - name: download user content
     ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
     dest: /tmp/user.zip

   - name: unzip user content
     ansible.builtin.unarchive:
     src: /tmp/user.zip
     dest: /app
     remote_src: yes

   - name: install npm dependencies
     community.general.npm:
     path: /app   

   - name: copy user service file
     ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

   - name: reload systemd daemon
     ansible.builtin.systemd:
     daemon_reload: yes
 
   - name: start and enable user service   
     ansible.builtin.service:
      name: user
      state: started
      enabled: yes