- name: Print variables with conditions
  hosts: localhost
  connection: local
  vars:
   NUMBER: 10
  tasks:
   - name: print if number is greater than 5
     ansible.builtin.debug:
       msg: "The number is greater than 5"
     when: NUMBER > 5
   - name: print if number is less than or equal to 5
     ansible.builtin.debug:
        msg: "The number is less than or equal to 5"
     when: NUMBER <= 5