- name: Print variables
  hosts: localhost
  connection: local
  vars:
    DURATION: 2months # this is a number
    COURSE: "DevOps with AWS" # this is a string
    AVAILABILITY: true # this is a boolean
    TOOLS: # this is a list[]
      - ansible
      - terraform
      - docker
    CONCEPTS: # this is a dictionary
      - CI: "Jenkins"
      - CD: "Gitlab"
     CI: Jenkins
     CD: Gitlab
  tasks:
   - name: Print course details
     ansible.builtin.debug:
      msg: "The course is {{ COURSE }}, with duration of {{ DURATION }}, the concepts discussed are{{ CONCEPTS }}, the tools used are {{ TOOLS }},  is the course all days {{AVAILABILITY}}"
