- name: functions
  hosts: local
  connection: local
  vars:
    person: "sameer,parvez,shaik"
  tasks:
    - name: print functions
      ansible.builtin.debug:
        msg: "Hello, {{ person | default('ll') }}"