- name: Hello World
  hosts: Frontend
  tasks: 
  - name: Print Hello World
    ansible.builtin.debug:
      msg: "Hello World"

- name: Hello World
  hosts: Local
  tasks:
   - name: Print Hello World
     ansible.builtin.debug:
       msg: "Hello World from localhost" 