- name: install pakages
  hosts: Frontend
  become: true
  tasks:
   - name: install packages
     ansible.builtin.package:
       name: "{{ item.name }}"
       state: "{{ item.state }}"
     loop:
      - { name: "mysql" , state: "absent" }
      - { name: "python" , state: "absent" }
      - { name: "redis" , state: "absent" }
      - { name: "nginx" , state : "absent" }
