- name: shell vs command
  hosts: Frontend
  tasks:
  - name: redirect output to a file using shell
    ansible.builtin.shell: "ls -ltr > /tmp/shell_output.txt"
    register : shell_output
  - name : print output
    ansible.builtin.debug:
      msg: "{{ shell_output.stdout }}"
