- name: Print variables with args
  hosts: localhost
  connection: local
  tasks:
    - name: Print variables with args
      ansible.builtin.debug:
        msg: "Hello {{name}}, your age is {{age}}"
      
     # ansible-playbook -i inventory.ini var-args.yaml -e "name=sameer" -e "age=23" --- cmd